### ISSUE TITLE
install problems & instructions

### ISSUE THREAD

**Issue by musicformellons** [screee/screess#129]
I am quite new in the javascript scene and having problems installing. Could you help me in the right direction please as I sure would like to use screess? This is the error message I get:

~/Downloads/screess-master$ sudo npm install -g .
npm WARN engine pngjs@0.4.0: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.14.2"})
npm ERR! Linux 4.1.0-040100rc6-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "."
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2
npm ERR! path /usr/lib/node_modules/screess/compiled/screess
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, chmod '/usr/lib/node_modules/screess/compiled/screess'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bom/Downloads/screess-master/npm-debug.log

and in the npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'install', '-g', 'screess-master.zip' ]
2 info using npm@2.14.2
3 info using node@v0.12.7
4 verbose node symlink /usr/bin/node
5 verbose install initial load of /usr/lib/package.json
6 verbose readDependencies loading dependencies from /usr/lib/package.json
7 silly cache add args [ 'screess-master.zip', null ]
8 verbose cache add spec screess-master.zip
9 silly cache add parsed spec { raw: 'screess-master.zip',
9 silly cache add   scope: null,
9 silly cache add   name: null,
9 silly cache add   rawSpec: 'screess-master.zip',
9 silly cache add   spec: '/home/bom/Downloads/screess-master.zip',
9 silly cache add   type: 'local' }
10 silly addLocalTarball shasum (computed) 1e614bacfb2aa593de509ab13b5007010a0385d2
11 verbose addTmpTarball /home/bom/Downloads/screess-master.zip not in flight; adding
12 verbose addTmpTarball validating metadata from /home/bom/Downloads/screess-master.zip
13 verbose tar unpack /home/bom/Downloads/screess-master.zip
14 verbose tar unpacking to /tmp/npm-4210-ed1632c6/unpack-cda708aaa8e9
15 silly gentlyRm /tmp/npm-4210-ed1632c6/unpack-cda708aaa8e9 is being purged
16 verbose gentlyRm don't care about contents; nuking /tmp/npm-4210-ed1632c6/unpack-cda708aaa8e9
17 silly gunzTarPerm modes [ '775', '664' ]
18 error not a package /home/bom/Downloads/screess-master.zip
19 error addLocal Could not install /home/bom/Downloads/screess-master.zip
20 verbose stack Error: ENOENT, open '/tmp/npm-4210-ed1632c6/unpack-cda708aaa8e9/package.json'
20 verbose stack     at Error (native)
21 verbose cwd /home/bom/Downloads
22 error Linux 4.1.0-040100rc6-generic
23 error argv "node" "/usr/bin/npm" "install" "-g" "screess-master.zip"
24 error node v0.12.7
25 error npm  v2.14.2
26 error path /tmp/npm-4210-ed1632c6/unpack-cda708aaa8e9/package.json
27 error code ENOENT
28 error errno -2
29 error enoent ENOENT, open '/tmp/npm-4210-ed1632c6/unpack-cda708aaa8e9/package.json'
29 error enoent This is most likely not a problem with npm itself
29 error enoent and is related to npm not being able to find a file.
30 verbose exit [ -2, true ]

**Comment by lucaswoj** [comment]
Sorry @musicformellons! This is really alpha-quality software right now. I'm in the process of overhauling the project's build system and broke the `npm` install temporarily :disappointed: I'll push a fix and update the docs this morning!

**Comment by musicformellons** [comment]
That would be great! Thx.

**Comment by lucaswoj** [comment]
@musicformellons All fixed now! I also updated the README with a few minor syntax changes. Please let me know if you have any more questions.
